version: '3.8'

services:
  app:
    build: .
    ports:
      - "3330:3330"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/sync-pad
      - SESSION_SECRET=your-production-session-secret
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
